volumes:
  mariadb:
    name: mariadb
    driver: local # local driver is used to bind the volume to the host
    driver_opts:
      device: ~/data/mariadb # path to the volume on the host
      o : bind # bind mounting host volume to the container
      type : none

  wordpress:
    name: wordpress
    driver: local # local driver is used to bind the volume to the host
    driver_opts:
      device: ~/data/wordpress # path to the volume on the host
      o : bind # bind mounting host volume to the container
      type : none


networks:
  tenet: # internal network for the services
    name: tenet


services:
  mariadb:
    container_name: mariadb
    image: mariadb:user
    build: requirements/mariadb
    env_file :
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - tenet
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:user
    build: requirements/wordpress
    env_file :
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - tenet
    depends_on:
     - mariadb
    restart: always

  nginx:
    container_name: nginx
    image: nginx:user
    build: requirements/nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443" # port forwarding for https
    networks:
      - tenet
    depends_on:
      - wordpress
    restart: always